# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: d8233ce
_src_path: https://github.com/algorand-devrel/simple-algokit-beaker-template
algod_port: '4001'
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: null
author_name: null
ide_vscode: true
indexer_port: '8980'
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
project_name: simp
python_linter: ruff
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true

